export type Photo = {
	img: string;
	imgGravity?: string;
	alt: string;
	title: string;
	date: string;
	where: string;
	text: string;
	bg: string;
};

export const PHOTOS: Array<Photo> = [
	{
		img: "bheu7bjpxjope5lxmf13",
		alt: "Newton the golden retriever sitting on his bottom on the turf field at doggy daycare on a bright summer day, smiling at the camera with squinting eyes",
		title: "I Love Daycare!",
		date: "2019-07-03",
		where: "Doggy Daycare, Ballard, WA",
		text: "I love spending the whole day at doggy daycare because I get to follow the people around and sometimes get sprayed by the water hose!",
		bg: "#667644"
	},
	{
		img: "k3ghueosgpotdxzugawc",
		alt: "Newton the golden retriever sitting on his bottom on the sidewalk at twilight. He is wearing his harness for a walk and looking quite cute.",
		title: "I Love Walks With Dad!",
		date: "2019-07-04",
		where: "Ballard, WA",
		text: "Sometimes Dad notices that I look extra cute on our walks and stops to take a picture, so I make sure to pose and make my ears as fluffy as I can!",
		bg: "#344966"
	},
	{
		img: "ywqoynsei8rfmidde6wp",
		alt: "Newton the golden retriever sitting very close to the camera with a concerned look on his face.",
		title: "I Haven't Eaten In Days",
		date: "2019-10-03",
		where: "Ballard, WA",
		text: "Through years of experimenting, I've found that the best way to let Mom and Dad know that I haven't eaten in like 3 days is to get right in their face and look concerned.",
		bg: "#5e676c"
	},
	{
		img: "gsvqyxf5ifqg3cc4f19d",
		alt: "Newton the baby golden retriever sitting on his bottom looking keenly up at the camera. He is next to his favorite dog toy and his tail is very small.",
		title: "Puppy Blubber!",
		date: "2013-03-31",
		where: "Fort Collins, CO",
		text: "I just woke up from a power nap, I found my favorite toy, and my fat rolls are lookin' extra cute — is it play time now?",
		bg: "#432725"
	},
	{
		img: "haigrsgsv0k4zelekodp",
		alt: "Newton the teenage golden retriever sitting on his bottom on top of a box that is too small to fully fit him. One of his legs hangs off the side and he seems ok with the fact that he may fall off.",
		title: "Balance Master",
		date: "2013-06-05",
		where: "Fort Collins, CO",
		text: "Sometimes I like to sit places that aren't quite big enough for me anymore, just to check and see how big I'm getting!",
		bg: "#2E2039"
	}
];

// TODO
// 	"aabcgr1z1xigo38uayqs",
// 	"aalfmnod60jgutmku4ip",
// 	"b1ldnjdlm3l7ebvg6mbq",
// 	"bacohhll8zmz5m5ubyry",
// 	"bqedjjh1sjnmt7bxcvvh",
// 	"bsbm7agmmdjwfzkeepnm",
// 	"bu05wed4xutcj0z5hk0h",
// 	"bwrcgmms2fhzw8srfb6b",
// 	"c2fscw9cwmmps7hihjgw",
// 	"ceogc8rvbm2ccwlhdo7m",
// 	"cgeoa5efm6umfpoqjtyg",
// 	"chrddnmp6lflc9ycw8zf",
// 	"cmb3usezfpcmrhqwlugc",
// 	"d0uissz1sg1brmxqygez",
// 	"d6rc5zniyscjbpkvgydt",
// 	"dehkjtz1gndipwcgsd1v",
// 	"df9orngzav0ogv2r7xhv",
// 	"dfgpe1yaavxpwhqbkogn",
// 	"dhc4odtgctbr68hm7ywr",
// 	"di4znyjftdkqvcwtorsc",
// 	"dvc10rbewbwxhzrqvrvb",
// 	"e3tguwt3jkwrohmr7ngo",
// 	"ei0mr3zkuxlcaulickbt",
// 	"eigo37ylbmoegok0ycgj",
// 	"eps4cxdxjtpzvzadftsk",
// 	"fuyfqdnn1eygwggv1rtp",
// 	"g6urjgbd5rapmkr9oevz",
// 	"gir6u3h71oe9elltqgya",
// 	"gjvmw2nhrdtutyg1clos",
// 	"gmym6ggmki4c2hsaa06l",
// 	"gqdv53yittuomx3xs3nw",
// 	"gynkhyt4qazu4tqt5wnb",
// 	"hih9mtheicvtqcvvuyil",
// 	"hmro982sochtce5gfe1r",
// 	"i0yh9ybkqltpwfy8y42f",
// 	"i97dozc0adnykciiamlr",
// 	"idw1x1sjtbhgmghchmpg",
// 	"idw82fdhupmuxi7okhtt",
// 	"inp8f8hxiy2p6hbq94oa",
// 	"iosphl1dtbvsavpzy2pr",
// 	"iuztnfaigsins8g6b74j",
// 	"jmsopszoui6h6g8z6yfa",
// 	"jopg8ur2vqvkfxrgjeoe",
// 	"k0lq3ejtzuzs5dm3hlvv",
// 	"k3n2mmj3bjr9iiv949ff",
// 	"kdpquf1lfwekacsk9acu",
// 	"kl6q0vvjzvnpewniwoji",
// 	"krgljmwwtqlimmdmk3ux",
// 	"ktwbhzymhioejotsxhbp",
// 	"kv3xj6xfx8xpwsrzzeix",
// 	"l2yxixtpgt83ozaccx65",
// 	"l90oinzelonj02yydd8w",
// 	"land8wgf2qpghtto9hhp",
// 	"lcapvtsxgt5fulj1djig",
// 	"lcfjq6doribzwsuetcoq",
// 	"lfeufq1dz0hgmndbkqs4",
// 	"lotwyyc7t402nz4w70t4",
// 	"lrd13fw0vhnyydgw4mwc",
// 	"lwnvaplwimz5d1sf7yj1",
// 	"lzmad0s6nl73k2jzewtv",
// 	"mctfkkux9mnt7ckmtkfd",
// 	"mfswpyudlwutwrq8zfd3",
// 	"mioru8odvwx5ye4xhimg",
// 	"mnovwfzutupp3apmvnpg",
// 	"mpetnqmn4xiku3l21bxd",
// 	"mptawo4fdm0txj9v3wlp",
// 	"myre0idrdyhapeujuh5a",
// 	"nabagccqnpkxqs5ylmf7",
// 	"ng19xkysjgvul7giyl1e",
// 	"nje8jngbzsv4mkwqlfw5",
// 	"nm0uztu2opbwsesjqsnd",
// 	"nsx0lhycjphzuwlqf6pg",
// 	"nym2yo6twuigq9q7ybkz",
// 	"ooirre6bqbezvay7ttfe",
// 	"ouiipf7y4mawwxxnb7xi",
// 	"ox83dxkdcpckcj9kkauh",
// 	"oxhinpxmfujblr6yxuhl",
// 	"p3thpx5kozyqw6idxopg",
// 	"pgqmmthb99uvlcimhcje",
// 	"pprfmezdezkrykrzexbe",
// 	"pupuih8t2ywtukr6at72",
// 	"pvswut1n5n16rmhfcmjs",
// 	"pvvqh12kk6mmkoo2r2tt",
// 	"q3lkrvq1nc5b5y3ngbpn",
// 	"q3yvdmwcdtymx1w28kjg",
// 	"q66lyuyaqtennevlqt0k",
// 	"qcam6dpbbwsd85amuqyw",
// 	"qctroyvnvimmcfeirmcr",
// 	"qdnbqmg6rfbvojo9uqyk",
// 	"qgqtdqlkfguafw2bv0rc",
// 	"qnl3ww8xa5nyg8xlcxbi",
// 	"qpyl963zuscpmjzgqbay",
// 	"qs0rsp3lyoiyio75wg4x",
// 	"qsftuanwuvr1hj8z0vck",
// 	"qv2q5oskk32erarrged0",
// 	"r247rwrn4xkmzjkbmzhq",
// 	"r4y1tltxou9djjuj47md",
// 	"rylmskhwo09ufiafac1o",
// 	"s8nmon4ruqtwcvwggzgn",
// 	"sdpiecctr25onoyeib8m",
// 	"t7olwc4qxrbf7xinqef6",
// 	"tavvzeufri62zxvu6vsb",
// 	"tbuhwwv1tcxypd9e49mr",
// 	"tcrnwtkjverv572z9ugc",
// 	"tdjw9trkke8ciwmkcbjv",
// 	"tfgabpda0w6m4wwvdzo4",
// 	"tnogygv1gu6ajtqehpv7",
// 	"toiku6bhxjaligtgzdgr",
// 	"u5f1s0geqtohycauj0oj",
// 	"udab6ged5b7vq7ezndun",
// 	"uphlz8ty1sd0xfcbahrc",
// 	"utxwd0cjjzpzo6qpfnq0",
// 	"uv2qlhtly5hfl39q88ku",
// 	"v0cbmke9rupkn8ac0m9i",
// 	"van04eqhhu9rsuovtjiv",
// 	"vfnuewejo8knfkcqs49o",
// 	"vp0wyb6brpzdtvws2xbc",
// 	"vq7accomh6fcf5lxi72u",
// 	"wcfzzknhehm2lwsifob4",
// 	"wervgcd1uqejzcimh85l",
// 	"wgxrhxpsxrovucptzfsn",
// 	"wheud06kqvv1qwtdbwqf",
// 	"ww9riikj7ghaglwfqen1",
// 	"wzm0zk7bazerdbt3lyj5",
// 	"x7uogjahyt9uejbf0aiz",
// 	"xj7yycdkejiogyo42ffv",
// 	"xmriqhvad2jxpt6ggqzt",
// 	"y5i3rc4cucf779mj74oz",
// 	"yaqqbzetnlgzdfdi2jct",
// 	"yb3kwcjvrir474cwzktr",
// 	"yjl3g18oys8na80m2mgg",
// 	"ylmuxmyz8szcmsgkq1ou",
// 	"yookin0waseqo5rk3vbq",
// 	"zbcp82kuehbh4apshrc4",
// 	"zkuuxfn0xumteyfghhrp",
// 	"zlzgd9cpkayf1moqsn4m",
// 	"zo9gmxvuddplqm4tzfjy",
// 	"zov5mopmlzmpqnqfganv",
