import { Links, LiveReload, Meta, Outlet, Scripts, ScrollRestoration, useLocation } from "@remix-run/react";
import { json, type LinksFunction, type LoaderFunction, type MetaFunction } from "@remix-run/server-runtime";
// @ts-ignore
import gameHash from "~/game/hash"; // auto-generated by scripts/build-game.ts
import { getUser } from "~/session.server";
import tailwindStylesheetUrl from "~/styles/index.css";
import { useSkipHydrate } from "~/utils";

export const links: LinksFunction = () => {
  return [{ rel: "stylesheet", href: tailwindStylesheetUrl }];
};

export const meta: MetaFunction = () => ({
  charset: "utf-8",
  title: "Good Boy Newton",
  viewport: "width=device-width,initial-scale=1",
});

type LoaderData = {
  user: Awaited<ReturnType<typeof getUser>>;
};

export const loader: LoaderFunction = async ({ request }) => {
  return json<LoaderData>({
    user: await getUser(request),
  });
};

export default function App() {
  const skipHydrate = useSkipHydrate();
  const location = useLocation();

  return (
    <html lang="en" className="h-full bg-amber-400">
      <head>
        <Meta />
        <Links />
      </head>
      <body className="h-full">
        <Outlet />
        <ScrollRestoration />
        {skipHydrate ? null : <Scripts />}
        <LiveReload />
        {location.pathname === "/" ? <script type="module" src={`/game/index-${gameHash}.js`}></script> : null}
      </body>
    </html>
  );
}
