import { useLoaderData } from "@remix-run/react";
import { json, type LoaderFunction } from "@remix-run/server-runtime";
// @ts-expect-error
import gameHash from "~/game/hash"; // auto-generated by scripts/build-game.ts
import { useOptionalUser } from "~/utils";

interface LoaderData {
  gameHash: string;
}

export const loader: LoaderFunction = async () => {
  const data: LoaderData = { gameHash };

  return json(data);
};

export default function Index() {
  const _user = useOptionalUser();
  const data = useLoaderData<LoaderData>();

  return (
    <main className="grid h-full place-items-center p-4">
      <div className="mb-80">
        <h1 className="font-game text-5xl">Good Boy Newton</h1>
        <p className="text-2xl">Newton is a very good boy {data.gameHash}</p>
      </div>
      <canvas id="game"></canvas>
      <script type="module" src={`/game/index-${data.gameHash}.js`}></script>
    </main>
  );
}
